insert into PRODUCT(PRODUCT_NAME, CURRENCY, PRICE, PRICE_EUR, UPDATE_DATE, CREATION_DATE)
values ('BOOK', 'EUR', 22.3, 22.3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('DVD', 'USD', 22.3, 21.3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
---