insert into EXCHANGE_RATE(ISO_CCY, EXCHANGE_RATE, UPDATE_DATE, CREATION_DATE)
values ('USD', 1.3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('CHF', 1.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('EUR', 1.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('YPN', 1.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
---